mode: dev
data:
  dev_paths: ['/work/harry87122/dataset/miniasr_data/dev-clean/data_list_sorted.json']
  text:
    mode: character
    vocab: /work/harry87122/dataset/miniasr_data/9h/vocab_char.txt

decode:
  type: greedy
  token: /work/harry87122/dataset/miniasr_data/train-clean-100/vocab_char.fl.txt
  lexicon: /work/harry87122/dataset/LibriSpeech/librispeech-char-lexicon.txt
  lm: /work/harry87122/dataset/LibriSpeech/4-gram.arpa
  beam_size: 100
  token_beam_size: 25
  beam_threshold: 100.0
  lm_weight: 2.0
  word_score: -1.0
  sil_score: 0.0
  log_add: False

hparam:
  val_batch_size: 32
  njobs: 16
  pin_memory: true

trainer:
  gpus: 1
  logger: false
  default_root_dir: model/ctc_base_fbank_10h_char
  deterministic: true
